### PR TITLE
feat: add props allow-negative

### PR DESCRIPTION
**Pull request by jeromeheissler**

### CODE REVIEW

**Comment by fengyuanchen** [comment]
Why? Where to use a negative time?

**Comment by angelformica** [comment]
This would be useful for me too

**Comment by jeromeheissler** [comment]
I use this plugin to see remaining time to prepare an order. And if we are late I would like to see it and not just see a countdown at 0.
you can see it in exemple there is a countdown with 5s left and it will not stop a the end

**Comment by fengyuanchen** [comment]
I don't think this is a common feature in life. In other words, it is not useful for most people.

**Comment by johnflash4real** [comment]
i need this negative feature too... was surprised its not supported our of the box

**Pull request closed without merging**
