### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by rashidpathiyil**

### CODE REVIEW

**Comment by fengyuanchen** [comment]
Why?

**Comment by rashidpathiyil** [comment]
> Why?
I think all the changes are an imporvement.
Let me know which part you think not required ?

**Comment by fengyuanchen** [comment]
IE is not supported as of v2.

**Comment by fengyuanchen** [comment]
`vue@3` is useful for people who come from vue2.

**Comment by rashidpathiyil** [comment]
People will copy paste the command like every other package install, no one adds vue on command

`npm i pkg` is always better

**Pull request closed without merging**
